FROM mcr.microsoft.com/dotnet/core/sdk:latest AS build
WORKDIR /app

# copy everything else and build app
COPY . /app
WORKDIR /app

# copy csproj and restore as distinct layers
COPY *.sln .
COPY Dream.AdminV2/*.csproj ./Dream.AdminV2/
RUN dotnet restore

RUN dotnet publish -c Release -o out


FROM mcr.microsoft.com/dotnet/core/aspnet:latest AS runtime
WORKDIR /app
COPY --from=build /app/Dream.AdminV2/out ./

#ÉèÖÃÊ±Çø
RUN /bin/cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
    && echo 'Asia/Shanghai' >/etc/timezone 

ENTRYPOINT ["dotnet", "Dream.AdminV2.dll"]
 