FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /app

# copy everything else and build app
COPY . /app
WORKDIR /app

# copy csproj and restore as distinct layers
COPY *.sln .
COPY Dream.DataApiV2/*.csproj ./Dream.DataApiV2/
RUN dotnet restore

RUN dotnet publish -c Release -o out


FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS runtime
WORKDIR /app
COPY --from=build /app/out ./

#ÉèÖÃÊ±Çø
RUN /bin/cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
    && echo 'Asia/Shanghai' >/etc/timezone 

ENTRYPOINT ["dotnet", "Dream.DataApiV2.dll"]
 