FROM mcr.microsoft.com/dotnet/core/sdk:2.2 AS build
WORKDIR /app

# copy everything else and build app
COPY . /app
WORKDIR /app

# copy csproj and restore as distinct layers
COPY *.sln .
COPY Dream.DataApi/*.csproj ./Dream.DataApi/
RUN dotnet restore

RUN dotnet publish -c Release -o out


FROM mcr.microsoft.com/dotnet/core/aspnet:2.2 AS runtime
WORKDIR /app
COPY --from=build /app/Dream.DataApi/out ./

#ÉèÖÃÊ±Çø
RUN /bin/cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
    && echo 'Asia/Shanghai' >/etc/timezone 

ENTRYPOINT ["dotnet", "Dream.DataApi.dll"]
 